export const dropdown = {
	Active: 'Active',
	Inactive: 'Inactive',
	NTE: 'NTE',
	NTEValue: '16',
	Target: 'Target',
	TargetValue: '17',
	MSP: 'MSP',
	HiringManager: 'HiringManager',
	HiringManagerValue: 'Hiring Manager',
	BillRateBased: 'BillRateBased',
	BillRateBasedValue: '7',
	MarkupBased: 'MarkupBased',
	MarkupBasedValue: '8',
	StaffingAgencyStandardMarkUpPercentage: 'StaffingAgencyStandardMarkUpPercentage',
	StaffingAgencyStandardMarkUpPercentageValue: '22',
	RateCard: 'RateCard',
	RateCardValue: '23',
	PeriodofPerformance: 'PeriodofPerformance',
	PeriodofPerformanceValue: '14',
	BudgetedHours: 'BudgetedHours',
	BudgetedHoursValue: '15',
	OTRateType: 'OTRateType',
	Activate: 'Activate',
	Deactivate: 'Deactivate',
	Disabled: 'Disabled',
	All: 'All',
	WageBasedOt: '3',
	BillRateBasedOt: '4',
	BillRateWageBasedOt: '5',
	STWageBasedOTMarkup: '6',
	Professional: 85,
	LightIndustrial: '84',
	Icsow: '86',
	BillRateBasedPro: 'Bill Rate Based (Professional only)',
	Probation: 'Probation',
	Potential: 'Potential',
	Status: 'StaffingAgencyStatusId',
	ProfessionalRate: 'Professional'

};
