import {
	ContainsValuePipe,
	ContainsNullPipe,
	BooleanPipe,
	MaskDigitsPipe,
	CountryCodePipe,
	CountryPhonePipe,
	SortingPipe,
	DisablePipe,
	SuffixPipe,
	PrefixPipe,
	NormaliseCamelcasePipe,
	ZipcodePipe,
	RemoveUnderscorePipe,
	YesNoPipe,
	SafePipe,
	CurrencyPipe,
	NumericPipe,
	MaskFormatPipe,
	EmailjsonPipe,
	PreserveFormatPipe
} from '@xrm-pipes';
// Exporting all pipes
export const pipes = [
	ContainsValuePipe,
	ContainsNullPipe,
	BooleanPipe,
	MaskDigitsPipe,
	CountryCodePipe,
	CountryPhonePipe,
	SortingPipe,
	DisablePipe,
	SuffixPipe,
	PrefixPipe,
	NormaliseCamelcasePipe,
	ZipcodePipe,
	RemoveUnderscorePipe,
	YesNoPipe,
	SafePipe,
	CurrencyPipe,
	NumericPipe,
	MaskFormatPipe,
	EmailjsonPipe,
	PreserveFormatPipe
];
